
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./commanComponents/Header";
import Footer from "./commanComponents/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import MainLayout from './MainLayout';

export const metadata = { //SSR
  title: "pradeep",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
          <Header/>
            {children}
            <Footer/>
        </MainLayout>
      </body>
    </html>
  );
}
